manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/KondratevYaroslav
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: soft_off
      import: app/west.yml
  self:
    path: config
